# Generated by Django 4.2.13 on 2024-05-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="last modified datetime"
            ),
        ),
    ]
