# Generated by Django 4.2.13 on 2024-05-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_reservation_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="ending_day",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="slot",
            name="starting_day",
            field=models.DateField(),
        ),
    ]
