# Generated by Django 4.2.13 on 2024-05-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_slot_ending_day_alter_slot_starting_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="info",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
